version: '2'
services:
    app:
        build: ./
        image: arthurtibame/swagger_api:v5
        container_name: app
        depends_on: 
          - mysql_db
        #volumes:
        #    - ./logs:/app/logs
        # ports:
        #   - "8082:8080"
    nginx:
        build: ./nginx
        container_name: nginx
        environment:
          - SERVER_NAME=modovision-api.eastasia.cloudapp.azure.com
        volumes:
           - ./logs:/var/log/nginx/
        ports:
          - "80:80"           
        restart: always
        

    mysql_db:
        image: mysql:5.6
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 2020aiot
            MYSQL_DATABASE: android_app
            MYSQL_USER: modovision
            MYSQL_PASSWORD: 2020aiot
    
#volumes:
#    mysql-data: 
